# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-06 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1name', models.CharField(max_length=120)),
                ('p2name', models.CharField(max_length=120)),
                ('p1email', models.EmailField(max_length=100)),
                ('p2email', models.EmailField(max_length=100)),
                ('p1mno', models.CharField(max_length=10)),
                ('p2mno', models.CharField(max_length=10)),
                ('time', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('pid', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
