# Generated by Django 2.0.1 on 2018-02-26 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=10)),
                ('ext', models.CharField(max_length=10)),
                ('time', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=10)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1name', models.CharField(max_length=120)),
                ('p2name', models.CharField(max_length=120)),
                ('p1email', models.EmailField(max_length=100)),
                ('p2email', models.EmailField(max_length=100)),
                ('p1mno', models.CharField(max_length=10)),
                ('p2mno', models.CharField(max_length=10)),
                ('time', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('q1_score', models.IntegerField(default=0)),
                ('q2_score', models.IntegerField(default=0)),
                ('q3_score', models.IntegerField(default=0)),
                ('q4_score', models.IntegerField(default=0)),
                ('q5_score', models.IntegerField(default=0)),
                ('q6_score', models.IntegerField(default=0)),
                ('subtime', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('gender1', models.IntegerField(default=0)),
                ('gender2', models.IntegerField(default=0)),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('completeques', models.CharField(max_length=120)),
                ('qid', models.IntegerField(default=0)),
                ('ac', models.IntegerField(default=0)),
                ('qlevel', models.IntegerField(default=0)),
                ('qsub', models.IntegerField(default=0)),
            ],
        ),
    ]
