# Generated by Django 2.0.1 on 2018-02-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gender1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gender2',
        ),
    ]
