# Generated by Django 2.0.1 on 2018-02-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCC', '0003_auto_20180227_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='completeques',
            field=models.CharField(max_length=5000),
        ),
    ]
