# Generated by Django 2.0.1 on 2018-02-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCC', '0005_auto_20180224_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='subtime',
            field=models.IntegerField(default=0),
        ),
    ]
