# Generated by Django 2.0.1 on 2018-02-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCC', '0008_questions_qlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='qsub',
            field=models.IntegerField(default=0),
        ),
    ]
